pleeb_words_list = [
    "acrotomophilia", "anal", "anilingus", "anus", "apeshit", "arsehole", "ass", "asshole", "assmunch", "autoerotic",
    "babeland", "bareback", "barenaked", "bastard", "bastardo", "bastinado", "bbw", "bdsm", "beaner", "beaners",
    "bimbos", "birdlock", "bitch", "bitches", "blowjob", "blumpkin", "bollocks", "bondage", "boner", "boob", "boobs",
    "bukkake", "bulldyke", "bullet", "bullshit", "busty", "butt", "buttcheeks", "butthole", "camgirl", "camslut",
    "camwhore", "carpetmuncher", "cialis", "circlejerk", "clit", "clitoris", "cock", "cocks", "coprolagnia",
    "coprophilia", "cornhole", "coon", "coons", "creampie", "cum", "cumming", "cumshot", "cumshots", "cunnilingus",
    "cunt", "darkie", "daterape", "deepthroat", "dendrophilia", "dick", "dildo", "dingleberry", "dingleberries",
    "doggiestyle", "dolcett", "domination", "dominatrix", "dommes", "dvda", "ecchi", "ejaculation", "erotic",
    "erotism", "escort", "eunuch", "fag", "faggot", "fecal", "felch", "fellatio", "feltch", "femdom", "figging",
    "fingerbang", "fingering", "fisting", "footjob", "frotting", "fuck", "fucks", "fuckin", "fucking", "fucktards",
    "fudgepacker", "futanari", "gangbang", "genitals", "goatcx", "goatse", "gokkun", "goodpoop", "googirl", "goregasm",
    "grope", "guro", "handjob", "hardcore", "hentai", "homoerotic", "honkey", "hooker", "horny", "incest",
    "intercourse", "jailbait", "jerkoff", "jigaboo", "jiggaboo", "jiggerboo", "jizz", "juggs", "kike", "kinbaku",
    "kinkster", "kinky", "knobbing", "livesex", "lolita", "lovemaking", "masturbate", "masturbating", "masturbation",
    "milf", "mong", "motherfucker", "muffdiving", "nambla", "nawashi", "negro", "neonazi", "nigga", "nigger", "nimphomania",
    "nipple", "nipples", "nsfw", "nude", "nudity", "nutten", "nympho", "nymphomania", "octopussy", "omorashi", "orgasm",
    "orgy", "paedophile", "paki", "panties", "panty", "pedobear", "pedophile", "pegging", "penis", "pikey", "pissing",
    "pisspig", "playboy", "pleasure", "poof", "poon", "poontang", "porn", "porno", "pornography", "pthc", "pubes",
    "pussy", "queaf", "queef", "quim", "raghead", "rape", "raping", "rapist", "rectum", "rimjob", "rimming", "sadism",
    "santorum", "scat", "schlong", "scissoring", "semen", "sex", "sexcam", "sexo", "sexy", "sexual", "sexually",
    "sexuality", "shemale", "shibari", "shit", "shits", "shitblimp", "shitty", "shota", "shrimping", "skeet", "slanteye",
    "slut", "smut", "snatch", "snowballing", "sodomize", "sodomy", "spastic", "spic", "splooge", "spooge", "spunk",
    "strapon", "strappado", "suck", "sucks", "swastika", "swinger", "taste", "threesome", "throating", "thumbzilla",
    "tushy", "twat", "twink", "twinkie", "undressing", "upskirt", "urethra", "urophilia", "vagina", "viagra",
    "vibrator", "voyeur", "voyeurweb", "voyuer", "vulva", "wank", "wetback", "wetdream", "whore", "worldsex", "xx",
    "xxx", "yaoi", "yiffy", "zoophilia"
]